name: CICD

on:
  pull_request:
    branches: [ main ]
  push:
jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: start uvicorn and run tests
      run: |
        export MONGO_URL=${{ secrets.MONGO_IP }}
        uvicorn app.main:app --host 0.0.0.0 --port 8000 & sleep 5
        python app/test_main.py
        
    - name: Build Docker image
      run: |
        docker build -t test-webapi:latest .

    - name: Push to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker tag test-webapi:latest ${{ secrets.DOCKERHUB_USERNAME }}/test-webapi:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-webapi:latest
